//
//  ListPullRequestRouter.swift
//  TopSwiftRepositories
//
//  Created by Thiago Cavalcante De Oliveira on 21/07/20.
//  Copyright (c) 2020 Thiago Cavalcante De Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListPullRequestRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ListPullRequestDataPassing {
    var dataStore: ListPullRequestDataStore? { get }
}

class ListPullRequestRouter: NSObject, ListPullRequestRoutingLogic, ListPullRequestDataPassing {
    weak var viewController: ListPullRequestViewController?
    var dataStore: ListPullRequestDataStore?

}
