//
//  ListPullRequestPresenter.swift
//  TopSwiftRepositories
//
//  Created by Thiago Cavalcante De Oliveira on 21/07/20.
//  Copyright (c) 2020 Thiago Cavalcante De Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
// This tag below is used to create the testable files from the Cuckoo pod
// CUCKOO_TESTABLE

import UIKit

protocol ListPullRequestPresentationLogic {
    func presentScreenLoading()
    func hideScreenLoading()
    func presentError(title: String, subtitle: String)
    func presentPullRequests(pullRequests: ListPullRequest.Response)
}

class ListPullRequestPresenter: ListPullRequestPresentationLogic {
    weak var viewController: ListPullRequestDisplayLogic?
    
    func presentScreenLoading() {
        viewController?.displayScreenLoading()
    }
    
    func hideScreenLoading() {
        DispatchQueue.main.asyncAfter(deadline: .now()+1) {
            self.viewController?.hideScreenLoading()
        }
    }
    
    func presentError(title: String, subtitle: String) {
        viewController?.displayError(title: title, subtitle: subtitle)
    }
    
    func presentPullRequests(pullRequests: ListPullRequest.Response) {
        let pullRequestsViewModelCell: [ListPullRequest.ViewModel] = pullRequests.pullRequests.compactMap {
            ListPullRequest.ViewModel(pullRequest: $0)
        }
        
        viewController?.displayPullRequests(pullRequestsViewModelCell)
    }
    
}
