//
//  ListPullRequestViewController.swift
//  TopSwiftRepositories
//
//  Created by Thiago Cavalcante De Oliveira on 21/07/20.
//  Copyright (c) 2020 Thiago Cavalcante De Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPullRequestDisplayLogic: class {
    func displayScreenLoading()
    func hideScreenLoading()
    func displayError(title: String, subtitle: String)
    func displayPullRequests(_ listPullRequestsViewModel: [ListPullRequest.ViewModel])
}

class ListPullRequestViewController: BaseListRepositoriesViewController {
    
    var interactor: ListPullRequestBusinessLogic?
    var router: (NSObjectProtocol & ListPullRequestRoutingLogic & ListPullRequestDataPassing)?
    var listPullRequestsViewModel: [ListPullRequest.ViewModel] = []
    
    func setup() {
        let viewController = self
        let interactor = ListPullRequestInteractor()
        let presenter = ListPullRequestPresenter()
        let router = ListPullRequestRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor?.getPullRequest()
    }
    
    override func setupNavigationBar() {
        title = "Pull Requests: " + (interactor?.getRepositoryName() ?? "")
    }
}

extension ListPullRequestViewController: ListPullRequestDisplayLogic {
    
    func displayPullRequests(_ listPullRequestsViewModel: [ListPullRequest.ViewModel]) {
        self.listPullRequestsViewModel = listPullRequestsViewModel
        tableView.reloadData()
    }
    
    
    func displayScreenLoading() {
        tableView.alpha = 0
        showScreenLoading()
    }
    
    func hideScreenLoading() {
        tableView.alpha = 1
        removeLoadingState()
    }
    
    func displayError(title: String, subtitle: String) {
        showError(title: title, message: subtitle)
    }
}

extension ListPullRequestViewController {
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return listPullRequestsViewModel.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = PullRequestCell()
        cell.configure(viewModel: listPullRequestsViewModel[indexPath.row])
        return cell
    }
    
    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 120
    }
}
